Navbar
CYPIAPT-LNDSE/sdm-app pull request #14
Opened 2017-01-31 14:46 UTC by esraajb

issues:
- hover on the home icon will changes the bg. tried alot of ways to change it, no success. same to "Questions" at the sidebar.

2017-01-31 16:26 UTC, des-des commented
@esraajb if this is not in progress, is it ready for review?

2017-02-01 10:09 UTC, njsfield approved these changes

2017-02-01 10:12 UTC, denesnori approved these changes

2017-02-01 10:16 UTC, njsfield requested changes
Refactoring before merging

2017-02-01 11:25 UTC, des-des commented
@njsfield @denesnori is this good to go? I see @njsfield has not approved

2017-02-01 11:26 UTC, njsfield approved these changes

2017-02-01 11:40 UTC, des-des requested changes

2017-02-01 11:40 UTC, des-des commented on index.html
> +      <li><a href="#!" id="1">How will this help me get better?</a></li>
`1` is ad name for id!

2017-02-01 11:40 UTC, des-des commented on css/style.css
> +.nav ul a:hover {
:fire:

2017-02-01 11:43 UTC, esraajb commented on index.html
> +      <li><a href="#!" id="1">How will this help me get better?</a></li>
this was edited in the other PR i made #15

2017-02-01 11:48 UTC, esraajb commented on css/style.css
> +.nav ul a:hover {
this was edited in the other PR i made #15

2017-02-01 11:51 UTC, des-des approved these changes

2017-02-01 11:52 UTC, merged